# Source Configuration
modelFeedingStage=false

sourcePort=1000
targetIp=161.97.123.208
targetPort=2000
maxConsideredMessagesExpected=500

# Variating Services Configuration
variatingServices.arrivalDelay=100
variatingServices.variatedServerLoadBalancerIp=144.91.87.61
variatingServices.variatedServerLoadBalancerPort=3000

variatingServices.qtdServices=1,2,3,4
mrtsFromModel=405597.23,203892.96,136603.74,102902.92
sdvsFromModel=1245.97,613.95,400.11,313.47
