# Source Configuration
modelFeedingStage=False

sourcePort=1000
targetIp=161.97.123.208
targetPort=2000
maxConsideredMessagesExpected=1000

# Variating Services Configuration
variatingServices.arrivalDelay=100
variatingServices.variatedServerLoadBalancerIp=144.91.87.61
variatingServices.variatedServerLoadBalancerPort=3000

variatingServices.qtdServices=1,2,3,4,5
mrtsFromModel=400327.83,195686.35,130058.15,97627.98,78290.86
sdvsFromModel=2291.45,1165.84,775.63,582.65,467.52