# Source Configuration
modelFeedingStage=False

sourcePort=1000
targetIp=loadbalancer1
targetPort=2000
maxConsideredMessagesExpected=500

# Variating Services Configuration
variatingServices.arrivalDelay=100
variatingServices.variatedServerLoadBalancerIp=loadbalancer2
variatingServices.variatedServerLoadBalancerPort=3000

variatingServices.qtdServices=1,2,3,4,5
mrtsFromModel=385327.83,185784.50,123351.34,92546.71,74193.78
sdvsFromModel=2778.40,1444.63,959.71,720.25,577.50
