# Source Configuration
modelFeedingStage=False

sourcePort=1000
targetIp=loadbalancer1
targetPort=2000
maxConsideredMessagesExpected=500

# Variating Services Configuration
variatingServices.arrivalDelay=200
variatingServices.variatedServerLoadBalancerIp=loadbalancer2
variatingServices.variatedServerLoadBalancerPort=3000

variatingServices.qtdServices=1,2,3,4,5
mrtsFromModel=431120.08,209640.47,138761.81,103951.46,83262.27
sdvsFromModel=1425.95,701.27,464.81,348.67,279.63
